language: node_js
node_js:
  - "11"
script: ./node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - echo "Travis iniciado corretamente."
before_script:
    - npm install
